---
title: "反波 Antiwave"
baseURL: "https://antiwave.github.io/"
theme: "zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Flypig"
  url: "http://flypig.net"
  avatar: "path/to/some-image.jpg"

outputs:
  home: ["HTML","RSS", "JSON"]
  section: ["HTML","RSS", "JSON"]

params:
  contact: "antiwave@tutanota.com"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The zen theme for Hugo example site."
  dateformat: "2 January, 2006"
  favicon: "icon-64.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "apple-touch-icon-180.png"
  image: "apple-touch-icon-180.png"
  imageMaxWidth: 400
  jquery: true
  mobileMenu: true
  poweredby: false
  search: true
  searchSize: 20
  sidebar: true
  submitted: true

podcast:
    title:                  # * Feed title, defaults to site title (iTunes).
    description:            # * Feed description/summary, defaults to  site description (iTunes).
    image:                  # * Feed image, place inside assets directory (iTunes).
    category:
      name:                 # * Feed category (iTunes).
      subcategories: []     # Feed sub category (iTunes).
    explicit: false    # Feed explicit settting, default to false (iTunes).
    author:  flypig               # Feed author (iTunes).
    owner:
      name:    热心小明             # Feed owner name (iTunes).
      email: antiwave@tutanota.com               # Feed owner e-mail (iTunes).
    lang:                   # Feed language, defaults to site language (iTunes).
    block: no           # Block the feed from iTunes, default to no (iTunes).
    complete: no        # Set the feed as complete, defaults to no (iTunes).
    type: episodic/serial   # Podcast type, defaults to episodic (iTunes).
    newfeed:                # Are you moving? Set the new feed url here (iTunes).
    cdn:                    # CDN url, no slash on end (https://cdn.example.org).
    preload: none/metadata/auto # Set on the HTML5 audio tag, defaults to "metadata".